### PR TITLE
Feat tls options

### PR DESCRIPTION
**Pull request by Xon**
- Fixes phpredis TLS support
- Expose TLS options to allow configuring the TLS connection.
- Fixes TLS tests to  actually tests TLS connects (and wow footguns).
- The TLS connection test is no-op'ed for php 5.6/7.1 due to SSL libraries being too old so they can't connect to redis v6 without significantly more troubleshooting.

### CODE REVIEW

**Comment by Xon** [comment]
@colinmollenhour once this is in, [Cm_Cache_Backend_Redis](https://github.com/colinmollenhour/Cm_Cache_Backend_Redis) probably should be updated to expose the additional username/password auth and TLS config.

**Comment by Xon** [comment]
@colinmollenhour any chance you'll have time to look at this?

**Comment by Xon** [comment]
https://www.php.net/manual/en/context.ssl.php
> Oddly, if "tls://" is set below, then TLSv1 is forced, but using "ssl://" allows TLSv1.2

and 
>Recommended use "ssl://" transport.
> in php 5.5 ~ 7.1
> ssl:// transport = ssl_v2|ssl_v3|tls_v1.0|tls_v1.1|tls_v1.2
> tls:// transport = tls_v1.0
> after 7.2 ssl:// and tls:// transports is same
> php 7.2 ~ 7.3 = tls_v1.0|tls_v1.1|tls_v1.2
> php 7.4 ~ 8.1 = tls_v1.0|tls_v1.1|tls_v1.2|tls_v1.3

**Comment by Xon** [comment]
Failed unit tests are because of #164

**Comment by colinmollenhour** [comment]
Looking good! I merged #164 if you want to update and give it another go.

**Comment by Xon** [comment]
All tests green now :)

**Comment by Xon** [comment]
With https://github.com/colinmollenhour/credis/pull/163#issuecomment-1120158187 I was able to remove the php version check and the tests work on all php versions :)

**Comment by colinmollenhour** [comment]
Excellent! Thanks @Xon and @waynetheisinger !

**Pull request merged**
