### PR TITLE
Allow versions in TLS

### LINKED ISSUE #133: New TLS support doesn't support versions in protocol identifier
UseCase
---
To connect to Digital Ocean Redis Cluster

Description
---
If you don't include the tslv1.2:// protocol identifier then Digital Ocean throws a 
```error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length```

I've got a fix for this and will submit a PR

### PR DESCRIPTION
**Pull request by waynetheisinger**
UseCase
---
To connect to Digital Ocean Redis Cluster

Description
---
If you don't include the tslv1.2:// protocol identifier then Digital Ocean doesn't connect.

Fixes #133

### CODE REVIEW

**Comment by waynetheisinger** [comment]
This PR replaces one that had gone stale due to recent commits https://github.com/colinmollenhour/credis/pull/134#issue-408865405

That one never got merged because for some reason Travis didn't like it. I never found the time to work out why. I'm hoping the updates to Travis config in recent commits in the core master will make this one pass... if not I might find some time to work out what the problem is... (well laid plans and all that.)

**Comment by colinmollenhour** [comment]
Thanks for updating the PR!

Unfortunately Travis appears to be broken.. Not sure if it is due to the migration from travis-ci.org to travis-ci.com or what.. I tried to migrate it but it says I have to be part of the beta for some reason..
image

I'll see if I can get accepted into the beta and get it migrated. I've not learned Github Actions well yet but if you know it well and want to submit a PR to migrate to it that would work too. :)

**Comment by colinmollenhour** [comment]
Ok I got it migrated and build on master is working. It should be configured to build Pull Requests as well. Can you push a new commit and hopefully that will trigger it. I couldn't trigger it manually since your branch is not in my repo.

**Comment by waynetheisinger** [comment]
I think I'll close this and do a new PR - this is cause I want to squash it so that create a clean and small patch using the https://github.com/colinmollenhour/credis/pull/153.patch functionality that I can point `vaimo/composer-patches` at. At the moment the patch has all the commits in it which offends my liking for tidy...

I will get this done today.

**Comment by waynetheisinger** [comment]
@colinmollenhour - I'm still getting `CredisException: Connection to Redis 127.0.0.1:6385 failed after 1 failures.` which is the same as before I updated the PR...

To debug this would you suggest I set up my fork to point at my own Travis account and debug it there?

**Pull request closed without merging**
