### PR TITLE
Test against redis v4 & test phpredis v4 (breaking API change for exists())

### PR DESCRIPTION
**Pull request by Xon**

### CODE REVIEW

**Comment by Xon** [comment]
(also kicks off against phpredis v4 with it's breaking API changes which I haven't nailed down yet)

**Comment by Xon** [comment]
I believe it is; [breaking changes for `exists()`](https://github.com/phpredis/phpredis/issues/1233)

credis documents `exists()` as returning an int anyway,

**Comment by Xon** [comment]
@colinmollenhour any chance you can merge this?

**Comment by colinmollenhour** [comment]
Will merging it negatively affect users of older versions? What negative affects is the lack of this change causing?

**Pull request merged**
