### PR TITLE
feat: Support 'tlsv1.2' protocol (see #154 and #133)

### LINKED ISSUE #133: New TLS support doesn't support versions in protocol identifier
UseCase
---
To connect to Digital Ocean Redis Cluster

Description
---
If you don't include the tslv1.2:// protocol identifier then Digital Ocean throws a 
```error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length```

I've got a fix for this and will submit a PR

### PR DESCRIPTION
**Pull request by colinmollenhour**
Merged #154 with latest master.

Fixes #133

### CODE REVIEW

**Comment by Xon** [comment]
@colinmollenhour let me rebase the TLS fixes; it was a rabbit hole to get working

**Comment by Xon** [comment]
#163 is where any sane TLS support needs to be based on. This library absolutely needs to expose TLS context options to make testing vaguely work and work with various RL setups.

**Comment by Xon** [comment]
@colinmollenhour I've included this into #163 which includes the `ssl://` transport option which is subtly different to `tls://` different for before php 7.2.

**Comment by colinmollenhour** [comment]
Replaced by #163

**Pull request closed without merging**
