### PR TITLE
Reformat code, update comment of Credis_Client __construct

### LINKED ISSUE #173: Re-format code with modern PHP style?
(I could help to propose a PR for it if it's accepted)

Modern:

https://github.com/colinmollenhour/credis/blob/dccc8a46586475075fbb012d8bd523b8a938c2dc/Client.php#L631-L650

Legacy:

https://github.com/colinmollenhour/credis/blob/dccc8a46586475075fbb012d8bd523b8a938c2dc/Client.php#L1051-L1062

Inconsistent indentation (space vs tab):

https://github.com/colinmollenhour/credis/blob/dccc8a46586475075fbb012d8bd523b8a938c2dc/Client.php#L988-L1027

### PR DESCRIPTION
**Pull request by wxiaoguang**
Close #173

I think the reformatting will improve the code's readability and maintainability.

* Use php-cs-fixer to re-format the code. 
* Remove unused (incorrect) consts: Credis_Client::VERSION, Credis_Client::FREAD_BLOCK_SIZE
* Update the comment of Credis_Client __construct: "Creates a Redisent connection" -> "Creates a connection" because there is no Redisent object anymore in code.

ps: feel free to edit on the PR directly

Diff without spaces: https://github.com/colinmollenhour/credis/pull/175/files?diff=split&w=1

### CODE REVIEW

**Comment by wxiaoguang** [comment]
hi @colinmollenhour , how do  you think about these changes?

**Comment by colinmollenhour** [comment]
Thanks for the PR! I would like to accept it but I think if all of the code is going to be reformatted it should get the full treatment and add PHP CS Fixer so it can be maintained easily. I recently did this with `Cm_Cache_Backend_Redis` so you could use that as a reference.

https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/blob/master/composer.json#L16
https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/blob/master/composer.json#L27
https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/blob/master/.php-cs-fixer.dist.php
https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/blob/master/.github/workflows/php.yml#L49-L50

**Comment by wxiaoguang** [comment]
> Thanks for the PR! I would like to accept it but I think if all of the code is going to be reformatted it should get the full treatment and add PHP CS Fixer so it can be maintained easily

OK, all done.

**Comment by colinmollenhour** [comment]
Nice work!
Agreed that CS Fixer is not needed but for one version.

**Pull request merged**
