### PR TITLE
Fix PHP 7.2 / PHPUnit 8.0 compatibility in unit tests

### PR DESCRIPTION
**Pull request by andrey-legayev**
Hi there,

I've tried to figure out the simplest fix for PHP 7.2 / PHPUnit 8 without total code duplication.
I've used proxy base class technique for this.

Pls check it when you have time

Cheers, 
Andrey

### CODE REVIEW

**Comment by andrey-legayev** [comment]
Nightly tests continue to fail, but that's caused by PHP 8.0.0-dev
It fails on trial to run "pecl install -f redis"

**Comment by colinmollenhour** [comment]
No objection to changing nightly to 7.3. I think 7.2 is failing because it must be using PHPUnit 8, but if we could run it with PHPUnit 7 it would probably pass.. Do you know an easy way to do this with Travis?

**Comment by andrey-legayev** [comment]
Switching to phpunit 7 is a great idea.
According to compatibility matrix PHPUnit 7 should be valid for PHP 7.1, 7.2 and 7.3:
https://phpunit.de/supported-versions.html

I've switched travis config and local phpunit env to PHP 7.2+PHPUnit 7. 
All tests are passing.
Please review new pull request: #114 

Changes in current pull request are valid only if you're planning to switch to PHPUnit 8

**Comment by andrey-legayev** [comment]
These changes are not needed anymore. I'm closing pull request.
Unit tests were fixed in #114

**Pull request closed without merging**
