### PR TITLE
Unit tests & multi/exec fixes

### PR DESCRIPTION
**Pull request by Xon**
More unit test fixes, and a little cleanup of the deprecated cluster class.

This gets all the tests* but the sentinel ones working.

*For php7.x, this requires phpredis 3.1.4 which isn't stable yet. So there is a hard-coded 'fail' rather than run the test and crash the unit tests.

Also includes more phpredis  vs standalone fixes plus more unit tests to verify

### CODE REVIEW

**Comment by Xon** [comment]
It took a bit of work, but all test run and pass under php 5.6, including cluster & sentinel tests :)

Only Pub sub fails on 7.x now :)

**Comment by Xon** [comment]
Unit tests should wait for slave replication to finish to prevent false positives now

**Comment by colinmollenhour** [comment]
Outstanding!

**Comment by colinmollenhour** [comment]
Thanks for your continued contributions, @Xon! I drafted a 1.9.0 release in case there are any BC breaking changes even though they are probably minor.

**Comment by Xon** [comment]
Sounds good!

**Pull request merged**
