### PR TITLE
fixed selected db bug

### PR DESCRIPTION
**Pull request by volkan**

### CODE REVIEW

**Comment by colinmollenhour** [comment]
Can you provide more detail about which issue this fixes? Just looking at the code it seems the 'db' is passed to the Credis_Client constructor so there should not be an issue or perhaps the issue is with Credis_Client? Note, Credis_Client doesn't call the select command until the connection is established whereas your patch immediately calls select upon instantiation so this is a minor behavior change.

Thanks!

**Comment by volkan** [comment]
@colinmollenhour of course;

if you want to select multiple db on redis, it doesn't work correctly.
For example;

````
$sentinel = new Credis_Sentinel(new Credis_Client('127.0.0.1',26379));
$cluster2 = $sentinel->getCluster('mymaster',3,0,true,true);
$cluster = $sentinel->getCluster('mymaster',2,0,true,true);
$cluster->set('test-1','value');
````
````
-> redis-cli -h localhost -n 2 -p 6381 GET "test-1"
(nil)
````

````
-> redis-cli -h localhost -n 3 -p 6381 GET "test-1"
"value"
````

**Comment by colinmollenhour** [comment]
I don't think your patch would fix this issue still since the second call to getCluster will return the same Credis_Cluster object that was created by the first call so there is just one object (constructor called only once). I suggest using one of the following:

```php
$sentinel = new Credis_Sentinel(new Credis_Client('127.0.0.1',26379));
$cluster2 = $sentinel->getCluster('mymaster',3,0,true,true);
...
$cluster = $sentinel->getCluster('mymaster')->all('select', 2);
$cluster->set('test-1','value');
```

Or if you want two separate connections/instances:

```php
$sentinel = new Credis_Sentinel(new Credis_Client('127.0.0.1',26379));
$cluster2 = $sentinel->getCluster('mymaster-3',3,0,true,true);
$cluster = $sentinel->getCluster('mymaster-2',2,0,true,true);
$cluster->set('test-1','value');
```

**Comment by volkan** [comment]
@colinmollenhour sorry I forget some commit. Fixed.

````
public function getCluster($name, $db=0, $replicas=128, $selectRandomSlave=true, $writeOnly=false)
    {
        if(!isset($this->_cluster[$name][$db])){
            $this->_cluster[$name][$db] = $this->createCluster($name, $db, $replicas, $selectRandomSlave, $writeOnly);
        }
        return $this->_cluster[$name][$db];
    }
````

**Comment by colinmollenhour** [comment]
Given that the client code can handle this more flexibly, why not do it one of the two ways I suggested instead of forcing the database index to be treated as part of the cluster name? This seems actually less intuitive to me.

**Comment by volkan** [comment]
I think, DB selection should be on cluster. Each cluster should be able to manage their own settings.
I am using like this;

````
sentinel.providers.sentinel_doctrine:
                sentinel:
                    host: "127.0.0.1"
                    port: "26379"
                    master_name: "mymaster"
                    namespace: "dcrc:"
                    db_index: "1"
                    random_slave:"true"
    sentinel.providers.sentinel:
                sentinel:
                    host: "127.0.0.1"
                    port: "26379"
                    master_name: "mymaster"
                    namespace: ""
                    db_index: "2"
    sentinel.providers.sentinel_nonflush:
                sentinel:
                    host: "127.0.0.1"
                    port: "26379"
                    master_name: "mymaster_nonflush"
                    namespace: ""
                    db_index: "0"
    sentinel.providers.sentinel_nf2:
                sentinel:
                    host: "127.0.0.1"
                    port: "26379"
                    master_name: "mymaster_nonflush"
                    namespace: ""
                    db_index: "3"
    sentinel.providers.sentinel_nf3:
                sentinel:
                    host: "127.0.0.1"
                    port: "26379"
                    master_name: "mymaster_nonflush"
                    namespace: ""
                    db_index: "4"
    sentinel.providers.sentinel_nf4:
                sentinel:
                    host: "127.0.0.1"
                    port: "26379"
                    master_name: "mymaster_nonflush"
                    namespace: ""
                    db_index: "5"
````

**Comment by ravi2jdesign** [comment]
Hi colinmollenhour,

Hope you are well,

I need your little help for redis cache issue, basically some time getting high load on server within 2 minute server load reach 200 to 300 %  and after flush magento cache it's back as normal within 2 minute. So I believe something is wrong with cache so when it's stuck hitting high load on server.
when you will get time please check my request and let me know if need any thing.
Many thanks in advance.

Thanks
Ravi

**Comment by colinmollenhour** [comment]
@ravi2jdesign I'm sorry, I don't offer tech support; the github repos are only for reporting bugs/issues. I suggest you read other issues that are already closed for ideas that may be applicable to your situation.

@volkan Thanks for the config example, that helps clarify a little. However, I still am not convinced that the db needs to be implicitly part of the key for `getCluster` method as it is really just a convenience wrapper for `createCluster` so you can get what you want like so:

```php
$sentinel = new Credis_Sentinel(new Credis_Client('127.0.0.1',26379));
$cluster2 = $sentinel->createCluster('mymaster', 3, 0, true, true);
$cluster = $sentinel->createCluster('mymaster', 2, 0, true, true);
$cluster->set('test-1','value');
```

If I was designing the API I'd probably prefer the `getCluster` method not even exist since it's purpose is somewhat subjective and really the caching of cluster instances should be handled at a higher level than the low-level library.

**Comment by volkan** [comment]
@colinmollenhour I think, master name (sentinel) and cluster name (client) must be different. This will solve the problem, what do you say?

**Comment by colinmollenhour** [comment]
I'm not sure I'm following you.. Please clarify what you are proposing.

**Comment by volkan** [comment]
For example (pseudo code);

```php
$cluster1Config = ['clusterName' => 'cluster-1', 'masterName' => 'mymaster', 'db' => 3]
$cluster2Config = ['clusterName' => 'cluster-2', 'masterName' => 'mymaster', 'db' => 2]
$sentinel = new Credis_Sentinel(new Credis_Client('127.0.0.1',26379));
$cluster1 = $sentinel->createCluster($cluster1Config);
$cluster2 = $sentinel->createCluster($cluster2Config);
```

Sentinel.php
```php
public function createCluster($configs)
{

       $name = $configs['clusterName']; 
       $masterName = $configs['masterName']; 
       $db=$configs['db'];
       ...
}
```

**Comment by colinmollenhour** [comment]
Yes, that is one way to solve the problem, but your first block of code would already work (except for signature change) since `createCluster` does not save an object instance in `$this->_cluster`, only the `getCluster` method does. So, to avoid breaking changes I suggest just ignoring the `getCluster` method and using `createCluster` or overriding or creating your own wrapper for it. E.g.

```php
class Volkan_Sentinel extends Credis_Sentinel {
  protected $_clusters = [];
  public function getCluster($name) {
    if ( ! isset($this->_clusters[$name])) {
      $conf = Volkan::config('clusters/'.$name);
      $this->_clusters[$name] = $this->createCluster($conf['master'], $cond['db'],...);
    }
    return $this->_clusters[$name];
  }
}
```

So I agree that the `getCluster` method is not great but on the other hand you don't have to use it at all and can easily step around it's limitations so I think I'd prefer to leave it be than break it to improve it.

**Pull request closed without merging**
