### PR TITLE
Revert the array constant, use the private static array again. This d…

### PR DESCRIPTION
**Pull request by aaajeetee**
…oes not break the PHP 5.4 and 5.5 compatibility

### CODE REVIEW

**Comment by Xon** [comment]
@aaajeetee you might as well preserve the lookup behaviour instead of the in_array linear search behaviour.

**Comment by colinmollenhour** [comment]
> @aaajeetee you might as well preserve the O(1) lookup behaviour instead of the in_array linear search behaviour.

Agreed, in_array is not efficient for something which will conceivably be used many many times. It might be a speculative micro-optimization but it is already there, just use a private static array as a hash with `isset()`. An optimized `preg_match` might be the fastest but would sacrifice code maintainability.

**Comment by aaajeetee** [comment]
Thanks for the feedback. I have used the array_key_exists() function call now, as it is in version 1.9.0.

**Comment by aaajeetee** [comment]
Also, is it an idea to update the travis file to also test PHP versions 5.4 and 5.5?

**Comment by colinmollenhour** [comment]
I added PHP 5.5 to the unit tests and got it passing. Is there a real use-case for officially supporting PHP 5.4? It actually passes currently but the number of places it is supported is dwindling..

https://travis-ci.org/colinmollenhour/credis/builds/283894536

**Comment by aaajeetee** [comment]
There isn't really a use-case for supporting PHP 5.4 I suppose, it's more the fact that this project supports PHP 5.4, so might as well test it.

But in the end that's your decision.

**Pull request merged**
