### PR TITLE
Update set() docs

### PR DESCRIPTION
**Pull request by Xon**

### CODE REVIEW

**Comment by Xon** [comment]
@colinmollenhour made the requested changes

**Comment by colinmollenhour** [comment]
Are you sure you pushed? Github is showing the original commit in the Changes tab still..

**Comment by Xon** [comment]
I think something is wonky after I did a rebase + force push

**Comment by Xon** [comment]
@colinmollenhour re-pushed the changes and fixed some other phpdocs errors.

**Pull request merged**
