### PR TITLE
Allow versions in TLS

### LINKED ISSUE #133: New TLS support doesn't support versions in protocol identifier
UseCase
---
To connect to Digital Ocean Redis Cluster

Description
---
If you don't include the tslv1.2:// protocol identifier then Digital Ocean throws a 
```error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length```

I've got a fix for this and will submit a PR

### PR DESCRIPTION
**Pull request by waynetheisinger**
UseCase
---
To connect to Digital Ocean Redis Cluster

Description
---
If you don't include the tslv1.2:// protocol identifier then Digital Ocean doesn't connect.

Fixes #133

### CODE REVIEW

**Comment by waynetheisinger** [comment]
It connects and can set and retrieve a key - but calling `Credis_Client->read_reply('hget')` still throws `error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length` - investigating further

**Comment by waynetheisinger** [comment]
Actually in a simple test script `hset` and `hget` now return values fine - however when they are being used by `Cm_Cache_Backend_Redis` they error out on about the fourth hget see screenshot:

Screenshot 2020-04-26 at 11 00 48

**Comment by waynetheisinger** [comment]
It is not a timeout:

```
require_once __DIR__.'/lib/Credis/Client.php';
$redis = new Credis_Client('tls://localhost:25061');
$redis->auth('password');
$redis->set('awesome', 'absolutely');
$redis->hSet('one','d','foo');
sleep(5);
$redis->hSet('two','d','bar');
sleep(5);
$redis->hSet('three','d','bah');
sleep(5);
$redis->hSet('four','d','fao');
sleep(5);
echo sprintf('<br>Hget equals? %s.<br>', $redis->hGet('one', 'd'));
sleep(5);
echo sprintf('<br>Hget equals? %s.<br>', $redis->hGet('two', 'd'));
sleep(5);
echo sprintf('<br>Hget equals? %s.<br>', $redis->hGet('three', 'd'));
sleep(5);
echo sprintf('<br>Hget equals? %s.<br>', $redis->hGet('four', 'd'));

die();
```
The above produces

```
Resource id #3
Hget equals? foo.

Hget equals? bar.

Hget equals? bah.

Hget equals? fao.
```

**Comment by Xon** [comment]
What version of php and openssl? It is possible your client libraries are out of date.

I recommend adjusting this PR to capture the negotiated protocal & cipher. Something like the following;
```php
if ($isTls) {
    $ctx = stream_context_create(['ssl' => [
        'capture_session_meta' => TRUE
    ]]);
} else {
    $ctx = null;
}

$result = $this->redis = @stream_socket_client(..., $ctx);

if ($result && $isTls) {
    $this->sslMeta = stream_context_get_options($ctx)['ssl']['session_meta'];
}
```
 ref: https://www.php.net/manual/en/migration56.openssl.php

**Comment by waynetheisinger** [comment]
Thanks @Xon I've done that - and it returns the meta as:

Screenshot 2020-04-27 at 13 21 03

**Comment by waynetheisinger** [comment]
I downgraded locally OpenSSL 1.0.1t but the problem remains so I don't think that version is the problem as both these versions should be supported.

**Comment by colinmollenhour** [comment]
1.0.1 and 1.1.0 are quite old and no longer supported (unless perhaps by the linux distro). Also PHP 5.6 is extremely old.. 

Check out https://github.com/rectorphp/rector I just learned about it recently, very impressive project.

**Comment by waynetheisinger** [comment]
I don't think it's a version issue - I did it on a fresh install of the same version of php and openssl and magento... and it works. It looks like it is a problem with my particular installation - is there any reason why redis over tls would baulk if ioncube was installed? I've used it for years over standard tcp with no issues.

**Comment by waynetheisinger** [comment]
OK yes it was a module - I think from my testing that PR now works if you want to code review with a potential to merge. The module that broke it was http://www.anowave.com/marketplace/magento-extensions/magento-google-tag-manager-enhanced-ecommerce-ua-tracking/

**Comment by colinmollenhour** [comment]
I don't want to merge code that increases complexity without a clear benefit. Can you explain under what circumstances this change is beneficial?

**Comment by waynetheisinger** [comment]
Yes If you don't include the tslv1.2:// protocol identifier then the Digital Ocean Redis Cluster doesn't connect. Presumably the same is true of other Redis providers using tls versions.

**Comment by colinmollenhour** [comment]
Would a documentation update be a better solution then?

**Comment by colinmollenhour** [comment]
Ahh, sorry I see there are a few changes needed still. But I think some of the changes can be left out like the passing a custom context and capturing `$this->sslMeta`?

**Comment by Xon** [comment]
The `sslMeta` is fairly useful debugging information, but there probably can be some cleanup so the `$isTls` variable is used earlier

**Comment by waynetheisinger** [comment]
I'll make the changes and recommit...

**Comment by mdTravis** [comment]
I've made the requested changes so this is ready to be considered again.

**Comment by waynetheisinger** [comment]
OK Travis is failing - all tests failing on "Connection to Redis 127.0.0.1:6385 failed after 1 failures."

can't see how my changes would have broken the connection but I'll test locally and report back.

**Comment by waynetheisinger** [comment]
Closed in favour of PR https://github.com/colinmollenhour/credis/pull/153

**Pull request closed without merging**
