### PR TITLE
Credis_Cluster - Fix hashing mechanism for array arguments

### PR DESCRIPTION
**Pull request by andrey-legayev**
Hi,

I've discovered interesting bug which appears only in cluster configuration.
The issue is when you send readonly command which accepts array as a parameter then I see following error in logs:
`Warning: md5() expects parameter 1 to be string, array given in {...}/magento2/vendor/colinmollenhour/credis/Cluster.php on line 260`

How to reproduce: 
 - configure Credis in master-slave mode, 2 slaves are enough
 - execute readonly command which has array argument, for example SINTER
 
Credis_Client handles such cases fine.
Credis_Cluster tries to perform md5() from PHP array which causing error shown above. The error is in hasing mechanism.

Array artuments are Ok for sInter command according to phpdoc comment in Credis_Client.php:
```
 * @method array|Credis_Client         sInter(mixed $keyOrArray, string $valueN = null)
```

**Fix:** I've added basic conversion from array to string for this specific case.

Please review my pull request when you have time.

The bug was found when we switched our Magento2 project to Redis cluster mode.
Our Magento2 uses Credis 1.8.2, but the bug must be actual in dev-master version as well.

Regards,
Andrey

### CODE REVIEW

**Comment by andrey-legayev** [comment]
hm.. seems like unit tests for php 7.2 are broken
I see the same error as in Master branch

**Comment by colinmollenhour** [comment]
Thanks for the fix, I've merged and tagged as 1.10.1. Note, I also updated the cache library to use random slave selection instead of the Credis_Cluster class since it is rather half-baked. See https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/pull/138

**Comment by andrey-legayev** [comment]
Thank you!

**Comment by andrey-legayev** [comment]
>Note, I also updated the cache library to use random slave selection ...
Tx for update. I'll review it.

**Comment by andrey-legayev** [comment]
I've checked most recent version - IMO looks good.  
For now we'll use Cluster configuration and later we'll switch to "load_from_slave" once Magento2 upgrades to fresh version of cache library.  
Our current version 1.8.2 supports only 1 slave and that's not suitable for our AWS ElastiCache setup.

**Pull request merged**
